### PR TITLE
Fix Windows build

### PR DESCRIPTION
**Pull request by mattn**

### CODE REVIEW

**Comment by floooh** [comment]
Hmm, this fix shouldn't be necessary, because link dependencies are defined via pragmas here:

https://github.com/floooh/qoiview/blob/ccc7ae1fa1b80716f243115d3855aba7a49aa6b8/sokol/sokol_app.h#L1713-L1720

What's your compiler toolchain? AFAIK both MSVC and Clang support the ```#pragma comment(lib, ...)``` approach.

**Comment by mattn** [comment]
pragma coment lib does not work on mingw64 gcc compiler.

**Comment by mattn** [comment]
Should I check with below?
```
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  # using GCC
endif()
```

**Comment by floooh** [comment]
> Should I check with below?
> 
> ```
> if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
>   # using GCC
> endif()
> ```

Might make sense yeah. I'm surprised though that only d3d11 needs to be linked. kernel32, user32, shell32, gdi32 and dxgi should also be required.

**Comment by floooh** [comment]
Closing this PR in favour of https://github.com/floooh/qoiview/pull/9 (which contains a couple of additional fixes)

**Pull request closed without merging**
